{"level":"error","message":"Unable to connect to database: ������������ \"user\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":116,"line":"329","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":116,"line":"329","name":"error","routine":"auth_failed","severity":"�����"},"stack":"SequelizeConnectionError: ������������ \"user\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\User\\Desktop\\EffectiveMobile\\history-service\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-11-19T19:06:39.786Z"}
